x-common-flink-config: &flink_image_pull_policy_config
  image: fh-flink-1.20.1
  build:
    context: ../../factorhouse-local/resources/flink/
    dockerfile: Dockerfile
  pull_policy: never

x-common-environment: &flink_common_env_vars
  AWS_REGION: us-east-1
  HADOOP_CONF_DIR: /opt/flink/conf
  HIVE_CONF_DIR: /opt/flink/conf
  # CUSTOM_JARS_DIRS: "/tmp/hadoop;/tmp/hive;/tmp/iceberg;/tmp/parquet"

x-common-flink-volumes: &flink_common_volumes
  - ../../factorhouse-local/resources/flink/bin/config.sh:/opt/flink/bin/config.sh:ro
  - ../../factorhouse-local/resources/flink/bin/flink-console.sh:/opt/flink/bin/flink-console.sh:ro
  - ../../factorhouse-local/resources/flink/bin/flink-daemon.sh:/opt/flink/bin/flink-daemon.sh:ro
  - ../../factorhouse-local/resources/flink/bin/sql-client.sh:/opt/flink/bin/sql-client.sh:ro
  - ./resources/flink-conf-1.yaml:/opt/flink/conf/flink-conf.yaml:ro
  - ../../factorhouse-local/resources/flink/hive-site.xml:/opt/flink/conf/hive-site.xml
  - ../../factorhouse-local/resources/flink/core-site.xml:/opt/flink/conf/core-site.xml
  - ../../factorhouse-local/resources/flink/init-catalogs.sql:/opt/flink/conf/init-catalogs.sql
  - ../../factorhouse-local/resources/deps/hadoop:/tmp/hadoop
  - ../../factorhouse-local/resources/deps/flink/hive/flink-sql-connector-hive-3.1.3_2.12-1.20.1.jar:/tmp/hive/flink-sql-connector-hive-3.1.3_2.12-1.20.1.jar
  - ../../factorhouse-local/resources/deps/flink/hive/antlr-runtime-3.5.2.jar:/tmp/hive/antlr-runtime-3.5.2.jar
  - ../../factorhouse-local/resources/deps/flink/iceberg:/tmp/iceberg
  - ../../factorhouse-local/resources/deps/flink/parquet:/tmp/parquet
  - ../../factorhouse-local/resources/deps/flink/connector:/tmp/connector

services:
  jobmanager-1:
    <<: *flink_image_pull_policy_config
    container_name: jobmanager-1
    command: jobmanager
    ports:
      - "18081:8081"
    networks:
      - factorhouse
    environment:
      <<: *flink_common_env_vars
    volumes: *flink_common_volumes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/config"]
      interval: 5s
      timeout: 5s
      retries: 5

  taskmanager-11:
    <<: *flink_image_pull_policy_config
    container_name: taskmanager-11
    command: taskmanager
    networks:
      - factorhouse
    environment:
      <<: *flink_common_env_vars
    volumes: *flink_common_volumes
    depends_on:
      jobmanager-1:
        condition: service_healthy

networks:
  factorhouse:
    external: ${USE_EXT:-true}
    name: factorhouse
