apiVersion: v1
kind: ConfigMap
metadata:
  name: kpow-config-files
  namespace: factorhouse
data:
  hash-rbac.yml: |
    admin_roles:
      - "kafka-admins"
      - "server-administrators"

    authorized_roles:
      - "kafka-admins"
      - "kafka-users"
      - "server-administrators"

    policies:
      - actions:
          - TOPIC_CREATE
          - TOPIC_PRODUCE
          - TOPIC_EDIT
          - TOPIC_DELETE
          - GROUP_EDIT
          - ACL_EDIT
          - BULK_ACTION
        effect: Allow
        resource:
          - cluster
          - "*"
        role: "kafka-admins"
      - actions:
          - CONNECT_CREATE
          - CONNECT_EDIT
        effect: Allow
        resource:
          - connect
          - "*"
        role: "kafka-admins"
      - actions:
          - SCHEMA_EDIT
          - SCHEMA_CREATE
        effect: Allow
        resource:
          - schema
          - "*"
        role: "kafka-admins"
      - actions:
          - BROKER_EDIT
        effect: Allow
        resource:
          - cluster
          - "*"
        role: "kafka-admins"
      - actions:
          - TOPIC_PRODUCE
          - TOPIC_EDIT
          - ACL_EDIT
        effect: Allow
        resource:
          - cluster
          - "*"
        role: "kafka-users"
      - actions:
          - CONNECT_CREATE
          - CONNECT_EDIT
        effect: Allow
        resource:
          - connect
          - "*"
        role: "kafka-users"
      - actions:
          - SCHEMA_EDIT
          - SCHEMA_CREATE
        effect: Deny
        resource:
          - schema
          - "*"
        role: "kafka-users"
      - actions:
          - TOPIC_INSPECT
        effect: Allow
        resource:
          - cluster
          - "*"
        roles: [ "kafka-users", "kafka-admins" ]
  hash-jaas.conf: |
    kpow {
            org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
            file="/etc/kpow/jaas/hash-realm.properties";
        };

    kpow_api {
            org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
            debug="true"
            file="/etc/kpow/jaas/hash-realm.properties";
        };
  hash-realm.properties: |
    # jetty/jetty
    jetty: MD5:164c88b302622e17050af52c89945d44,kafka-users,content-administrators
    # admin/admin
    admin: CRYPT:adpexzg3FUZAk,server-administrators,content-administrators,kafka-admins
    # other/other
    other: OBF:1xmk1w261u9r1w1c1xmq,kafka-admins,kafka-users
    # plain/plain
    plain: plain,content-administrators
    # user/password
    user: password,kafka-users
