services:
  kpow:
    image: factorhouse/kpow-ce:latest
    container_name: kpow-ce
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./kpow/config/setup.env
      - ${KPOW_LICENSE:-kpow/config/license.env}
    mem_limit: 2G
    volumes:
      - ./kpow/jaas:/etc/kpow/jaas
      - ./kpow/rbac:/etc/kpow/rbac
